### ISSUE TITLE
Release 2023 

### ISSUE THREAD

**Issue by 22388o** [AreaLayer/HyperArm#2]
**Pre Beta**

- [x] Final tests and finalize JSON
- [x] Integration with Hyperdrive and Hyperswarm
- [x] Files moved for Core and scripts separated 

**Beta**

- [x] Announcement on Twitter, Telegram and Nostr
